---
- hosts: all
  connection: local
  gather_facts: false
  become: false

  vars:

  tasks:
    - name: Ensure Environment Is Set Up
      ansible.builtin.include_tasks: setup_env.yml

    - name: Download Fabric Access Policies
      cisco.aci.aci_rest:
        path: "/api/node/mo/uni/infra.json?query-target=subtree&rsp-subtree=full&rsp-prop-include=config-only"
        method: get
        host: "{{ ansible_host }}"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: no
      register: funcprof

    - name: debug
      ansible.builtin.debug:
        var: funcprof

    - name: Copy to files
      ansible.builtin.copy:
        content: "{{ funcprof.imdata | to_nice_json }}"
        dest: "{{ role_path }}/files/iac-nac/{{ inventory_hostname }}/fabric_access_policies.json"