---
- name: Generate Access Policies file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/access_policies.nac.j2"
    dest: "{{ role_path }}/files/iac-nac/{{ inventory_hostname }}/access_policies.nac.yml"

- name: Generate Interface Policy Groups file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/access_interface_policy_groups.nac.j2"
    dest: "{{ role_path }}/files/iac-nac/{{ inventory_hostname }}/access_leaf_interface_policy_groups.nac.yml"

- name: Output Terraform Nexus-As-Code templates for Leaf Interface Profiles
  ansible.builtin.template:
    src: "{{ role_path }}/templates/access_leaf_interface_profiles.nac.j2"
    dest: "{{ role_path }}/files/iac-nac/{{ inventory_hostname }}/access_leaf_interface_profiles_{{ item }}.nac.yaml"
  loop: "{{ polUni | json_query('[].infraInfra.children[].infraAccPortP.attributes.name') | sort }}"
  vars:
    search_string: "[].infraInfra.children[?infraAccPortP.attributes.name==`{{ item }}`][].infraAccPortP"
    infraAccPortP: "{{ polUni | json_query(search_string) | first }}"
