---
- name: Output Terraform
  ansible.builtin.template:
    src: "{{ role_path }}/templates/fabric_policies.nac.j2"
    dest: "{{ role_path }}/files/iac-nac/{{ inventory_hostname }}/fabric_policies.nac.yaml"
