---
- name: Generate Pod Policies File
  ansible.builtin.template:
    src: "{{ role_path }}/templates/pod_policies.nac.j2"
    dest: "{{ role_path }}/files/iac-nac/{{ inventory_hostname }}/pod_policies.nac.yml"
